version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build . --file Dockerfile --tag my-image-name:latest

workflows:
  build-and-deploy:
    jobs:
      - build-docker-image
